const CATALOG = [
    {
        id: '1',
        name: 'Встраиваемый светильник Markt',
        price: '5060 ₽',
        discountStatus: 'Yes',
        priceWithDiscount: '3490 ₽',
        image: './src/catalog/images/1.png',
    },
    {
        id: '2',
        name: 'Линейный светильник ARG',
        price: '6700 ₽',
        discountStatus: 'no',
        priceWithDiscount: '',
        image: './src/catalog/images/2.png',
    },
    {
        id: '3',
        name: 'Светодиодный светильник',
        price: '6060 ₽',
        discountStatus: 'Yes',
        priceWithDiscount: '5060 ₽',
        image: './src/catalog/images/3.png',
    },
    {
        id: '4',
        name: 'Встраиваемый светильник Markt',
        price: '3490 ₽',
        discountStatus: 'no',
        priceWithDiscount: '',
        image: './src/catalog/images/4.png',
    },
    {
        id: '5',
        name: 'Линейный светильник ARG',
        price: '6060 ₽',
        discountStatus: 'Yes',
        priceWithDiscount: '5700 ₽',
        image: './src/catalog/images/5.png',
    },
    {
        id: '6',
        name: 'Светодиодный светильник',
        price: '5060 ₽',
        discountStatus: 'no',
        priceWithDiscount: '',
        image: './src/catalog/images/6.png',
    },
    {
        id: '7',
        name: 'Встраиваемый светильник Markt',
        price: '6060 ₽',
        discountStatus: 'Yes',
        priceWithDiscount: '3490 ₽',
        image: './src/catalog/images/7.png',
    },
    {
        id: '8',
        name: 'Линейный светильник ARG',
        price: '6700 ₽',
        discountStatus: 'no',
        priceWithDiscount: '',
        image: './src/catalog/images/8.png',
    },
]
export default CATALOG